cineland_accueil:
   path: /accueil
   controller: App\Controller\cineland\Cineland::accueil
   
cineland_init:
   path: /init
   controller: App\Controller\cineland\Cineland::init
   
cineland_menu:
   path: /menu
   controller: App\Controller\cineland\Cineland::menu
   
action:
   resource: action/routes.yaml
   prefix: /action